version: '3'

services:
  mongodb:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - .:/usr/database

  app:
    container_name: smartlist-api
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    build: .
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb
