version: '3'

services:
  app:
    build: .
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    links:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - ./src/database:/data/db
    ports:
      - '27017:27017'
